---

networks:
  proxy:
    external: true

#volumes:
  #certs:
    #external: true

services:
  dnsmasq:
    command: ["dnsmasq", "-C", "/app/templates/dnsmasq/dnsmasq.conf.dnsmasq_IOT"]
    container_name: ddns-update-dnsmasq-1
    image: dockurr/dnsmasq:2.92
    restart: on-failure
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - ./templates/dnsmasq:/app/templates/dnsmasq:ro
      - ./templates/openwrt/usr/lib/dnsmasq/dhcp-script.sh:/usr/lib/dnsmasq/dhcp-script.sh:ro
      - ./templates/openwrt/usr/share/libubox/jshn.sh:/usr/share/libubox/jshn.sh:ro
    environment:
      - "TZ=America/Chicago"
      - "LC_TIME=C.UTF-8"
      - "DNSMASQ_LOG_DHCP=1"
      #- "DNS1=1.0.0.1"
      #- "DNS2=1.1.1.1"

  ddns_update:
    build:
      context: .
      dockerfile: "Dockerfile"
    command: ["ddns_update", "-c", "/app/config/app.yml", "-l", "DEBUG", "del", "ce:5e:bb:xx:xx", "127.0.0.1", "test"]
    container_name: ddns-update-1
    restart: on-failure
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
      #- ./config/app.yml:/usr/local/etc/app.yml:ro
    environment:
      - "TZ=America/Chicago"
      - "LC_TIME=C.UTF-8"
      - "DNSMASQ_DOMAIN=wifi.home.arpa"
      - "DNSMASQ_LOG_DHCP=1"
    # >> Feel free to store sensitive data, such as your API host passphrase,
    # >> in a separate environment file.
    env_file:
      - ".env.compose"

