[build-system]
requires = [
  "setuptools>=61.0"
]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.11"
name = "update_ddns_zone"
version = "1.1.0"
description = "DDNS DHCP update integration with DNSMASQ"
readme = { file = "README.md", content-type="text/markdown" }
license = "BSD-3-Clause"
license-files = ["LICENSE.md"]
authors = [{ name = "Jeffrey Carpenter", email = "1329364+i8degrees@users.noreply.github.com" }]
maintainers = [{ name = "Jeffrey Carpenter", email = "1329364+i8degrees@users.noreply.github.com" }]
keywords = [ "ddns", "dhcp", "dnsmasq", "powerdns", "pdns" ]
classifiers = [
    "Development Status :: 3 - Alpha",
#"Development Status :: 4 - Beta",
#"Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: System Administrators",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3",
    # !! OpenWRT v24.10.4 requires this particular version
    "Programming Language :: Python :: 3.11",
    "Topic :: Utilities",
    "Topic :: Software Development :: Embedded Systems",
    "Topic :: System :: Networking :: Monitoring",
    "Topic :: System :: Networking",
]

dependencies = [
  "urllib3 >= 2.6.3",
  # !! OpenWRT v24.10.4 requires this particular version
  "pyyaml == 6.0.1",
  "Jinja2 >= 3.1.6",
]

[project.optional-dependencies]
dev = [
  # ?? Is this dependency necessary to include for `python3 -m build`
  "setuptools >= 61.0",
  "validate-pyproject[all]",
  "mypy==1.19.1",
  # !! TODO Verify whether or not we still need this dep
  "types-requests==2.32.4.20260107",
  "typing_extensions==4.15.0",
]

[project.urls]
"Homepage" = "https://github.com/i8degrees/update_ddns_zone.git"
"Issues" = "https://github.com/i8degrees/update_ddns_zone.git"
"Repository" = "https://github.com/i8degrees/update_ddns_zone.git"

[project.scripts]
ddns_update = "app.__main__:main"
# ?? utils should not be an executable
#utils = "utils.__main__:main"
#ddns_update_tests = "test.__main__:main"
# !! Future impl updates
#ddns_update = "app.ddns_update:main"
#ddns_psupdate = "psupdate.__main__:main"
#ddns_nsupdate = "nsupdate.__main__:main"
#build = "scripts.build:main"
#lint = "lint:main"

#[tool.setuptools]
#py-modules = ["build", "deploy", "test", "ddns_update"]

